
version: '2.0'
services:
  todos:
    ports:
    - "8000:8080"
    image:
      docker.pkg.github.com/sokube/simple-todo-list/simple-todo-list:latest
    environment:
      DB_USER: "todos-user"
      DB_HOST: "database"
      DB_NAME: "todos"
      DB_PORT: 5432
      DB_PASSWORD: "mysecretpassword"
    depends_on:
      - database
    
  database:
    image:
        postgres:alpine
    environment: 
      POSTGRES_DB: "todos"
      POSTGRES_USER: "todos-user"
      POSTGRES_PASSWORD: "mysecretpassword"
